CREATE TABLE IF NOT EXISTS customers (
    id BIGSERIAL PRIMARY KEY,
    customer_code VARCHAR(50) NOT NULL UNIQUE,
    customer_name VARCHAR(200) NOT NULL,
    print_name VARCHAR(200),
    customer_group VARCHAR(100),
    customer_type VARCHAR(100),
    territory VARCHAR(100),
    industry VARCHAR(100),
    status VARCHAR(50) DEFAULT 'Active',
    pricing_group VARCHAR(100),
    tax_invoice BOOLEAN DEFAULT TRUE,
    einvoice BOOLEAN DEFAULT FALSE,
    ewaybill BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    address TEXT,
    delivery_address TEXT,
    city VARCHAR(100),
    state VARCHAR(100),
    pincode VARCHAR(20),
    country VARCHAR(100) DEFAULT 'India',
    phone VARCHAR(30),
    mobile VARCHAR(30),
    email VARCHAR(150),
    website VARCHAR(200),
    fax VARCHAR(50),
    gst_type VARCHAR(100),
    gstin VARCHAR(30),
    gst_state VARCHAR(100),
    pan_no VARCHAR(30),
    cin_no VARCHAR(50),
    msme_no VARCHAR(50),
    msme_type VARCHAR(50),
    tds_applicable BOOLEAN DEFAULT FALSE,
    tcs_applicable BOOLEAN DEFAULT FALSE,
    currency VARCHAR(50),
    payment_terms VARCHAR(100),
    credit_limit NUMERIC(14, 2),
    credit_days INTEGER,
    discount NUMERIC(6, 2),
    ledger_group VARCHAR(100),
    opening_balance NUMERIC(14, 2),
    opening_balance_type VARCHAR(5) DEFAULT 'Dr',
    transport_mode VARCHAR(100),
    transporter VARCHAR(150),
    delivery_terms VARCHAR(150),
    lead_days INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
